view: orders_2026 {

  sql_table_name: `astrafy-test-507518.analytics.ex6_orders_2026_segmented` ;;

  label: "Orders 2026"

  description:
    "One row per order placed in 2026, including revenue, product quantity, customer and customer segment."

  # ===========================
  # Dimensions
  # ===========================

  dimension: order_id {
    label: "Order ID"
    description: "Unique identifier of an order."
    primary_key: yes
    type: number
    sql: ${TABLE}.order_id ;;
  }

  dimension: customer_id {
    label: "Customer ID"
    description: "Unique identifier of the customer."
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension_group: order {
    label: "Order Date"
    description: "Date on which the order was placed."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.order_date ;;
  }

  dimension: order_segmentation {
    label: "Customer Segment"
    description:
      "Customer classification based on prior 12-month ordering behaviour.
       New = 0 previous orders,
       Returning = 1-3 previous orders,
       VIP = 4 or more previous orders."
    type: string
    sql: ${TABLE}.order_segmentation ;;
  }

  dimension: quantity_of_products {
    label: "Product Quantity"
    description: "Total quantity of products purchased in the order."
    type: number
    sql: ${TABLE}.qty_product ;;
  }

  # Optional - only if added to ex6_orders_2026_segmented
  # dimension: product_id {
  #   label: "Product ID"
  #   description: "Unique identifier of the product."
  #   type: number
  #   sql: ${TABLE}.product_id ;;
  # }

  # ===========================
  # Measures
  # ===========================

  measure: total_revenue {
    label: "Total Revenue"
    description: "Total revenue generated by selected orders."
    type: sum
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
  }

  measure: total_orders {
    label: "Total Orders"
    description: "Distinct number of orders."
    type: count_distinct
    sql: ${order_id} ;;
  }

  measure: total_customers {
    label: "Total Customers"
    description: "Distinct number of customers."
    type: count_distinct
    sql: ${customer_id} ;;
  }

  measure: total_product_quantity {
    label: "Total Product Quantity"
    description: "Total product quantity across all selected orders."
    type: sum
    sql: ${quantity_of_products} ;;
  }

  measure: average_order_value {
    label: "Average Order Value"
    description: "Average revenue generated per order."
    type: number
    sql: SAFE_DIVIDE(${total_revenue}, ${total_orders}) ;;
    value_format_name: decimal_2
  }

  measure: average_products_per_order {
    label: "Average Products Per Order"
    description: "Average quantity of products included in an order."
    type: number
    sql: SAFE_DIVIDE(${total_product_quantity}, ${total_orders}) ;;
    value_format_name: decimal_2
  }

  measure: record_count {
    label: "Record Count"
    description: "Number of rows in the dataset."
    type: count
  }

  # ===========================
  # Aliases (optional)
  # ===========================

  measure: order_count {
    hidden: yes
    type: count_distinct
    sql: ${order_id} ;;
  }

  measure: customer_count {
    hidden: yes
    type: count_distinct
    sql: ${customer_id} ;;
  }

  measure: total_net_sales {
    hidden: yes
    type: sum
    sql: ${TABLE}.net_sales ;;
  }

}