view: orders_2026 {
  sql_table_name: `astrafy-test-507518.analytics.ex6_orders_2026_segmented` ;;

  label: "Orders 2026"
  description: "One row per order placed in 2026, including revenue, product quantity, customer, and customer segment."

  dimension: order_id {
    label: "Order ID"
    description: "Unique identifier of an order."
    primary_key: yes
    type: number
    sql: ${TABLE}.order_id ;;
  }

  dimension: customer_id {
    label: "Customer ID"
    description: "Unique identifier of the customer who placed the order."
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension_group: order {
    label: "Order Date"
    description: "Date on which the order was placed."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.order_date ;;
  }

  dimension: order_segmentation {
    label: "Customer Segment"
    description: "Order-level customer segment based on the number of orders placed by the customer during the prior 12 months. New means 0 prior orders, Returning means 1 to 3, and VIP means 4 or more."
    type: string
    sql: ${TABLE}.order_segmentation ;;
  }

  dimension: quantity_of_products {
    label: "Product Quantity"
    description: "Total quantity of products included in the order."
    type: number
    sql: ${TABLE}.qty_product ;;
  }

  measure: order_count {
    label: "Number of Orders"
    description: "Distinct number of orders."
    type: count_distinct
    sql: ${order_id} ;;
    drill_fields: [
      order_id,
      customer_id,
      order_date,
      order_segmentation,
      net_sales
    ]
  }

  measure: customer_count {
    label: "Number of Customers"
    description: "Distinct number of customers who placed orders."
    type: count_distinct
    sql: ${customer_id} ;;
    drill_fields: [customer_id, order_count, total_net_sales]
  }

  measure: total_net_sales {
    label: "Net Sales"
    description: "Total net sales generated by the selected orders."
    type: sum
    sql: ${TABLE}.net_sales ;;
    value_format_name: decimal_2
    drill_fields: [
      order_id,
      customer_id,
      order_date,
      order_segmentation,
      net_sales
    ]
  }

  measure: average_order_value {
    label: "Average Order Value"
    description: "Total net sales divided by the distinct number of orders."
    type: number
    sql: SAFE_DIVIDE(${total_net_sales}, ${order_count}) ;;
    value_format_name: decimal_2
  }

  measure: total_product_quantity {
    label: "Total Product Quantity"
    description: "Total quantity of products across the selected orders."
    type: sum
    sql: ${quantity_of_products} ;;
  }

  measure: average_products_per_order {
    label: "Average Products per Order"
    description: "Total product quantity divided by the distinct number of orders."
    type: number
    sql: SAFE_DIVIDE(${total_product_quantity}, ${order_count}) ;;
    value_format_name: decimal_2
  }
}